Home/urls.py
#!/usr/bin/env python
# encoding: utf-8

from django.conf.urls import url

from . import views

app_name = 'Home'
urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
]

WorkHome/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('Home.urls'))
]

Home/models.py
from django.db import models

# Create your models here.


class MonitorTask(models.Model):
    task_name = models.CharField(max_length=200)
    task_host = models.CharField(max_length=200)
    task_status = models.CharField(max_length=1)

    def __str__(self):
        return f"{self.task_host}:{self.task_name}"

Home/views.py
from django.shortcuts import get_object_or_404, render
from django.utils import timezone
from django.views import generic

from .models import MonitorTask
# Create your views here.


class HomeView(generic.ListView):
    template_name = 'Home/index.html'
    context_object_name = 'monitor_task_list'

    def get_queryset(self):
        return MonitorTask.objects.all()


def Home(request):
    return render(request, 'Home/index.html', {})

Home/templates/Home/index.html
{% load static %}
<html lang="zh-CN">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>WorkHome</title>

        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'Home/css/Home.css' %}" />
    </head>
    <body>
        <!-- Static Narbar -->
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">我的工作台</a>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="{% url 'Home:home' %}">首页</a></li>
                        <li><a href="admin">后台</a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>

        <!-- Home Body -->
        <div class="container">
            <div class="starter-template">
                {% if monitor_task_list %}
                    <h1>服务器在线任务列表</h1>
                    <br/>
                    <table class="table .table-bordered">
                        {% for task in monitor_task_list %}
                            <tr>
                                {% if task.task_status == 'F' %}
                                    <td><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></td>
                                {% elif task.task_status == 'E' %}
                                    <td><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span></td>
                                {% else %}
                                    <td><span class="glyphicon glyphicon-ok" aria-hidden="true"></span></td>
                                {% endif %}
                                <td>{{ task.task_name }}</td>
                                <td>{{ task.task_host }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                {% else %}
                    <h1>没有发现服务器在线任务列表</h1>
                {% endif %}
            </div>
        </div><!-- /.container -->

        <!-- Bootstrap core JavaScript -->
        <script type="text/javascript" src="{% static 'js/jquery.js' %}" ></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.js' %}" ></script>

        <!-- myself's JavaScript -->
        <script type="text/javascript">
            window.setInterval("window.location.reload()", 60000);
        </script>
    </body>
</html>